/* Auto-generated */
window.RECIPES = [
  {
    "slug": "lablabi-tounsi",
    "title": "لبلابي تونسي أصلي",
    "emoji": "🥙",
    "category": "char",
    "categoryLabel": "أكل شارع",
    "totalTime": "20",
    "yield": "4",
    "difficulty": "سهلة",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Chickpea_and_Pasta_Soup_%28Laabali%29.jpg/800px-Chickpea_and_Pasta_Soup_%28Laabali%29.jpg",
    "imageAlt": "طبق لبلابي تونسي — حمص وهريسة وخبز مقرمش",
    "featured": true
  },
  {
    "slug": "brik-tounsi",
    "title": "بريك تونسي بالتونة والبيض",
    "emoji": "🥟",
    "category": "char",
    "categoryLabel": "أكل شارع",
    "totalTime": "30",
    "yield": "4",
    "difficulty": "متوسطة",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Brik.jpg/800px-Brik.jpg",
    "imageAlt": "بريك تونسي مقلي ذهبي محشي بالتونة",
    "featured": true
  },
  {
    "slug": "fricasse-tounsi",
    "title": "فريكاسي تونسي",
    "emoji": "🌯",
    "category": "char",
    "categoryLabel": "أكل شارع",
    "totalTime": "30",
    "yield": "6",
    "difficulty": "متوسطة",
    "image": "https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?auto=compress&cs=tinysrgb&w=800",
    "imageAlt": "فريكاسي تونسي ساندويتش مقلي",
    "featured": true
  },
  {
    "slug": "chakchouka-tounsia",
    "title": "شكشوكة تونسية",
    "emoji": "🍳",
    "category": "malha",
    "categoryLabel": "مالحة يومية",
    "totalTime": "30",
    "yield": "4",
    "difficulty": "سهلة",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Shakshuka.jpg/800px-Shakshuka.jpg",
    "imageAlt": "شكشوكة تونسية بالبيض والطماطم",
    "featured": false
  },
  {
    "slug": "youyou-tounsi",
    "title": "يويو تونسي",
    "emoji": "🍩",
    "category": "halawiyat",
    "categoryLabel": "حلويات تونسية",
    "totalTime": "50",
    "yield": "30",
    "difficulty": "متوسطة",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Baklava%2C_Tunisian_style.jpg/800px-Baklava%2C_Tunisian_style.jpg",
    "imageAlt": "يويو تونسي حلوة مقرمشة",
    "featured": false
  },
  {
    "slug": "salade-mechouia",
    "title": "سلطة مشوية تونسية",
    "emoji": "🥗",
    "category": "salatat",
    "categoryLabel": "سلطات ومقبلات",
    "totalTime": "35",
    "yield": "4",
    "difficulty": "سهلة",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Mecheouia_Salad.jpg/800px-Mecheouia_Salad.jpg",
    "imageAlt": "سلطة مشوية تونسية ملونة",
    "featured": false
  },
  {
    "slug": "makroud-tounsi",
    "title": "مقروض تونسي بالتمر",
    "emoji": "🍯",
    "category": "halawiyat",
    "categoryLabel": "حلويات تونسية",
    "totalTime": "70",
    "yield": "25",
    "difficulty": "صعبة",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Makroudh.jpg/800px-Makroudh.jpg",
    "imageAlt": "مقروض تونسي بالتمر",
    "featured": true
  },
  {
    "slug": "bamia-billahm",
    "title": "بامية باللحم",
    "emoji": "🫛",
    "category": "malha",
    "categoryLabel": "مالحة يومية",
    "totalTime": "75",
    "yield": "4",
    "difficulty": "متوسطة",
    "image": "https://images.pexels.com/photos/566566/pexels-photo-566566.jpeg?auto=compress&cs=tinysrgb&w=800",
    "imageAlt": "بامية خضراء باللحم في صلصة طماطم",
    "featured": false
  },
  {
    "slug": "kosksi-hout",
    "title": "كسكسي بالحوت",
    "emoji": "🐟",
    "category": "kosksi",
    "categoryLabel": "كسكسي",
    "totalTime": "90",
    "yield": "6",
    "difficulty": "متوسطة",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Couscous-2.jpg/800px-Couscous-2.jpg",
    "imageAlt": "كسكسي بالحوت والخضرة",
    "featured": true
  },
  {
    "slug": "kosksi-djaj",
    "title": "كسكسي بالدجاج والخضرة",
    "emoji": "🍗",
    "category": "kosksi",
    "categoryLabel": "كسكسي",
    "totalTime": "120",
    "yield": "6",
    "difficulty": "متوسطة",
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Couscous-2.jpg/800px-Couscous-2.jpg",
    "imageAlt": "كسكسي تونسي بالدجاج والخضرة",
    "featured": true
  }
];
