/* Auto-generated from data/recipes.json */
window.RECIPES = [
  {
    "slug": "lablabi-tounsi",
    "title": "لبلابي تونسي أصلي",
    "emoji": "🥙",
    "category": "char",
    "categoryLabel": "أكل شارع",
    "totalTime": "20",
    "yield": "4",
    "difficulty": "سهلة",
    "image": "https://images.unsplash.com/photo-1512058567297-8c084a1a8932?w=800&q=80&auto=format&fit=crop",
    "imageAlt": "طبق لبلابي تونسي — حمص وهريسة وخبز مقرمش",
    "featured": true
  },
  {
    "slug": "brik-tounsi",
    "title": "بريك تونسي بالتونة والبيض",
    "emoji": "🥟",
    "category": "char",
    "categoryLabel": "أكل شارع",
    "totalTime": "30",
    "yield": "4",
    "difficulty": "متوسطة",
    "image": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80&auto=format&fit=crop",
    "imageAlt": "بريك تونسي مقلي ذهبي محشي بالتونة",
    "featured": true
  },
  {
    "slug": "fricasse-tounsi",
    "title": "فريكاسي تونسي",
    "emoji": "🌯",
    "category": "char",
    "categoryLabel": "أكل شارع",
    "totalTime": "30",
    "yield": "6",
    "difficulty": "متوسطة",
    "image": "https://images.pexels.com/photos/6605200/pexels-photo-6605200.jpeg?auto=compress&cs=tinysrgb&w=800",
    "imageAlt": "فريكاسي تونسي ساندويتش مقلي",
    "featured": true
  },
  {
    "slug": "chakchouka-tounsia",
    "title": "شكشوكة تونسية",
    "emoji": "🍳",
    "category": "malha",
    "categoryLabel": "مالحة يومية",
    "totalTime": "30",
    "yield": "4",
    "difficulty": "سهلة",
    "image": "https://images.unsplash.com/photo-1645112411341-6c4fd023314a?w=800&q=80&auto=format&fit=crop",
    "imageAlt": "شكشوكة تونسية بالبيض والطماطم",
    "featured": false
  },
  {
    "slug": "youyou-tounsi",
    "title": "يويو تونسي",
    "emoji": "🍩",
    "category": "halawiyat",
    "categoryLabel": "حلويات تونسية",
    "totalTime": "50",
    "yield": "30",
    "difficulty": "متوسطة",
    "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80&auto=format&fit=crop",
    "imageAlt": "يويو تونسي حلوة مقرمشة",
    "featured": false
  },
  {
    "slug": "salade-mechouia",
    "title": "سلطة مشوية تونسية",
    "emoji": "🥗",
    "category": "salatat",
    "categoryLabel": "سلطات ومقبلات",
    "totalTime": "35",
    "yield": "4",
    "difficulty": "سهلة",
    "image": "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80&auto=format&fit=crop",
    "imageAlt": "سلطة مشوية تونسية ملونة",
    "featured": false
  },
  {
    "slug": "makroud-tounsi",
    "title": "مقروض تونسي بالتمر",
    "emoji": "🍯",
    "category": "halawiyat",
    "categoryLabel": "حلويات تونسية",
    "totalTime": "70",
    "yield": "25",
    "difficulty": "صعبة",
    "image": "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&q=80&auto=format&fit=crop",
    "imageAlt": "مقروض تونسي بالتمر",
    "featured": true
  },
  {
    "slug": "bamia-billahm",
    "title": "بامية باللحم",
    "emoji": "🫛",
    "category": "malha",
    "categoryLabel": "مالحة يومية",
    "totalTime": "75",
    "yield": "4",
    "difficulty": "متوسطة",
    "image": "https://images.unsplash.com/photo-1604909052743-94e838986c24?w=800&q=80&auto=format&fit=crop",
    "imageAlt": "بامية خضراء باللحم في صلصة طماطم",
    "featured": false
  },
  {
    "slug": "kosksi-hout",
    "title": "كسكسي بالحوت",
    "emoji": "🐟",
    "category": "kosksi",
    "categoryLabel": "كسكسي",
    "totalTime": "90",
    "yield": "6",
    "difficulty": "متوسطة",
    "image": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b779?w=800&q=80&auto=format&fit=crop",
    "imageAlt": "كسكسي بالحوت والخضرة",
    "featured": true
  },
  {
    "slug": "kosksi-djaj",
    "title": "كسكسي بالدجاج والخضرة",
    "emoji": "🍗",
    "category": "kosksi",
    "categoryLabel": "كسكسي",
    "totalTime": "120",
    "yield": "6",
    "difficulty": "متوسطة",
    "image": "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80&auto=format&fit=crop",
    "imageAlt": "كسكسي تونسي بالدجاج والخضرة",
    "featured": true
  }
];
